### ISSUE TITLE
Fails to build with the current version

### ISSUE THREAD

**Issue by midwan** [georgik/sdl2-android-example#1]
## Expected behavior
Cloning the repo, installing the requirements (gradle version, SDK build tools version, etc) should allow the project to sync/build fully.

## Actual behavior
After installing all dependencies, the build fails with an error:
`Error:Exception thrown while executing model rule: NdkComponentModelPlugin.Rules#createNativeBuildModel(NativeBuildConfig, ModelMap<AndroidBinaryInternal>, ModelMap<NdkAbiOptions>, NdkHandler) > create(debug-armeabi-v7a)
Shared library runtime files D:\Github\sdl2-android-example\distribution\SDL2\lib\armeabi-v7a\libSDL2.so does not exist for prebuilt shared library 'SDL2:armeabi-v7aDebugShared'.`

## Steps to recreate
- Use the latest version of Android Studio.
- Clone this repo.
- Open project in Android Studio, follow the prompts to install any missing dependencies.
- The error comes up during the background gradle build.

**Comment by georgik** [comment]
@midwan Thank you for reporting the issue.
I recommend to use gradle from command line to avoid any issues cause by Android Studio.
Please try to run gradle task: distributeLib.
It should generate the missing file.
You can find more details in: https://github.com/georgik/sdl2-android-example/blob/master/README.md
Or in the series of articles related to build of SDL2 for Android:
https://georgik.rocks/sdl2_image-for-android-with-jpeg-image-format/

I see one possible solution - to add dependency to gradle build between distributeLib and default task launched by Android Studio.

**Comment by midwan** [comment]
@georgik 
I tried that, but I'm afraid it didn't work either:

```
D:\Projects\sdl2-android-example>c:\Gradle\gradle-4.5.1\bin\gradle distributeLib

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Projects\sdl2-android-example\app\build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [class 'com.android.build.gradle.model.AndroidComponentModelPlugin']
   > Gradle version 4.0 is required. Current version is 4.5.1. If using the gradle wrapper, try editing the distributionUrl in D:\Projects\sdl2-android-example\gradle\wrapper\gradle-wrapper.properties to gradle-4.0-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

Opening up `gradle-wrapper.properties`: 
```
#Thu Feb 22 16:50:00 CET 2018
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.0-all.zip

```

I tried `git reset --hard` and `git clean -f` first, to make sure nothing was altered by Android Studio of course...

**Comment by midwan** [comment]
@jojomickymack 
Hm, it still doesn't work for me I'm afraid. And I tried running it from the console first, as I wrote in my example above.

I'd really love to get a base environment like this up and running, so I can port a project I have over to Android, but so far it's been a rather frustrating adventure just getting the basic things to compile. This project seemed like the most promising one, if only it would work for me :P

**Comment by georgik** [comment]
There is new Gradle Wrapper inside the project. It works with latest Android Studio and Gradle 4.4.
I was testing also Gradle 4.7 and it produces the same error like reported by @midwan .
Please try this gradlew from the project.
Thank you.
