### ISSUE TITLE
feature request - add SDL2_gfx

### ISSUE THREAD

**Issue by jojomickymack** [georgik/sdl2-android-example#3]
gfx is the only missing child library - it's of debatable use since opengl is available, but is really a drop in library that would be fitting here.
http://www.ferzkopp.net/wordpress/2016/01/02/sdl_gfx-sdl2_gfx/

how to add to the project - 
1. add SDL2_gfx folder, add SDL2_gfx module to settings.gradle
2. copy the build.gradle from the SDL2_mixer module, change mixer to gfx where it appears.
3. add an entry in the main module's build.gradle referencing the include directory and shared library

```
SDL2_gfx {
    headers.srcDir "../SDL2_gfx/include"
    binaries.withType(SharedLibraryBinary) {
        sharedLibraryFile = file("${gradle.libDistributionRoot}/SDL2_gfx/lib/${targetPlatform.getName()}/libSDL2_gfx.so")
    }
}
```
4. Download the gfx library from ferzkopp's site, put the .h files in the gfx's include directory (5 files), put the .c files in the src folder. Remove the c files with 'test' in the name (4 files).
5. From the command line, you can run gradle :SDL2_gfx:distributeLib just like the others, and it will compile and link against SDL2.
6. Now you can include the gfx headers in your main.cpp file and use it like normal.
```
#include "SDL2_gfxPrimitives.h"
```

**Comment by georgik** [comment]
@jojomickymack Thank you for the feature request and for detailed manual.
SDL2_gfx is now part of the sdl2-android-example.

Please test whether it works for you. Thank you very much.
