### ISSUE TITLE
Cannot install generated app

### ISSUE THREAD

**Issue by zertyz** [georgik/sdl2-android-example#7]
After a "gradle build" command, I tried to, unsuccessfully, install the APK.

When copying to the device and installing from there, no errors was shown other than "App not installed".

When trying to install via adb, the error INSTALL_PARSE_FAILED_CERTIFICATE_ENCODING was shown, as in the logs bellow:

[luiz@pinklap sdl2-android-example]$ adb install app/build/outputs/apk/release/app-release-unsigned.apk 
Performing Streamed Install
adb: failed to install app/build/outputs/apk/release/app-release-unsigned.apk: Failure [INSTALL_PARSE_FAILED_CERTIFICATE_ENCODING: Failed to collect certificates from /mnt/expand/f3b8f369-8f3f-4841-8459-bce7a0d64239/app/vmdl1029592497.tmp/base.apk: android.content.pm.PackageParser$PackageParserException: Package /mnt/expand/f3b8f369-8f3f-4841-8459-bce7a0d64239/app/vmdl1029592497.tmp/base.apk has no certificates at entry AndroidManifest.xml: Package /mnt/expand/f3b8f369-8f3f-4841-8459-bce7a0d64239/app/vmdl1029592497.tmp/base.apk has no certificates at entry AndroidManifest.xml]

I am new to Android and don't know how to proceed from there.

**Comment by zertyz** [comment]
I could install the debug APK:

[luiz@pinklap sdl2-android-example]$ adb install app/build/outputs/apk/debug/app-debug.apk 
Performing Streamed Install
Success

**Comment by georgik** [comment]
Hi @zertyz . It seems that release version is not properly signed.
Are you able to install it from Android Studio or just from Gradle command line?
Are you able to generate signed release version from Android Studio?
Thank you for answers.

**Comment by Tanishq-Banyal** [comment]
You need to sign the release apk in order to install it on newer devices.

Or you can use the debug apk, it's pre-signed with temporary key.

**Comment by georgik** [comment]
Closing the issue. Feel free to reopen in case of newer problem.
